from __future__ import annotations

from enum import Enum
from typing import Any
from pydantic import BaseModel, Field

from core.result import DiagnosticStatus, Severity


class ConfidenceLevel(str, Enum):
    VERY_HIGH = "VERY HIGH"  # >= 90%
    HIGH = "HIGH"            # >= 75%
    MEDIUM = "MEDIUM"        # >= 50%
    LOW = "LOW"              # < 50%

    @classmethod
    def from_score(cls, score: float) -> "ConfidenceLevel":
        if score >= 0.90:
            return cls.VERY_HIGH
        if score >= 0.75:
            return cls.HIGH
        if score >= 0.50:
            return cls.MEDIUM
        return cls.LOW


class Recommendation(BaseModel):
    """
    Actionable remediation step for a diagnosed issue.
    """
    action: str
    command: str | None = None
    rationale: str
    priority: int = 1  # 1 = primary/immediate, 2 = secondary/investigative


class DiagnosedIssue(BaseModel):
    """
    An identified root-cause problem generated by the Rule Engine.
    """
    rule_id: str
    title: str
    category: str
    severity: Severity
    confidence: float = Field(ge=0.0, le=1.0)
    confidence_level: ConfidenceLevel
    root_cause: str
    correlated_evidence: list[str] = Field(default_factory=list)
    recommendations: list[Recommendation] = Field(default_factory=list)
    suppressed_rules: list[str] = Field(default_factory=list)


class DiagnosisReport(BaseModel):
    """
    Comprehensive diagnostic report synthesizing all observations.
    """
    timestamp: str
    target_host: str
    total_probes: int
    healthy_probes: int
    degraded_probes: int
    failed_probes: int
    status: DiagnosticStatus
    verdict: str
    issues: list[DiagnosedIssue] = Field(default_factory=list)
    key_observations: list[str] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)
